### ISSUE TITLE
Tracking issue: Editorial Overhaul to Namespaces

### ISSUE THREAD

**Issue by bumblefudge** [ChainAgnostic/CAIPs#91]
- [x] Open #92 for CAIP-92 (defines namespaces)
   - [x] Add namespace template (by analogy to CAIP template)
- [x] Create an entry in /namespace/ for each of the blockchain-specific CAIPs { 3, 4, 5, 6, 7, 13, 23, 24, 25, 26, 28, 30, [75], 76, [77, 78] }, linking to commit-specific (archival) links to each superceded CAIP as they will later be "deleted" at their simple URLs
   - [x] EIP155 + ERC20 + ERC721 + ERC1155 {3, 21, 22, 29} - [in review](https://github.com/ChainAgnostic/namespaces/pull/2)
   - [x] BIP122 {4} - [in review](https://github.com/ChainAgnostic/namespaces/pull/3)
   - [x] Cosmos {5} - [in review](https://github.com/ChainAgnostic/namespaces/pull/4)
   - [x] LIP9 {6}
   - [x] EOSIO {7} - [in review](https://github.com/ChainAgnostic/namespaces/pull/5)
   - [x] Polkadot {13} - [in review](https://github.com/ChainAgnostic/namespaces/pull/6)
   - [x] Filecoin {23}
   - [x] Tezos {26}
   - [x] Stellar {28}
   - [x] Solana {30}
   - [x] Hedera {76, #75 , #78 , #79 }
   - [ ] ~GPG and Radicle [#66 and #53]~ deferred until scope of CASA defined more explicitly
- [x] "Delete" each CAIP listed above from CAIPs repo (closes #68)
- [x] Update table of contents

**Comment by bumblefudge** [comment]
closed by #113
